/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smarttransport;

/**
 *
 * @author mursalat
 */
import java.sql.*;
import javax.swing.JOptionPane;
import static smarttransport.admin.*;

public class confirmTicket extends javax.swing.JFrame {

    /**
     * Creates new form confirmTicket
     */
    public confirmTicket() {
        initComponents();
        
//        fid =""+10;
//        NID = ""+10000;
        
        try
        {
            con = DriverManager.getConnection(server,"root", "awd@3456");
            stmt = (Statement) con.createStatement();
            stmt.execute("use smart;");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Connection Failed");
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void doTicket()
    {
        try
        {
            String code;
            String seat="";
            int s;
            r1 = stmt.executeQuery("select seat from flight where flightID ="+fid+";");
            r1.next();
            s = r1.getInt(1)+1;
            int i;
            for(i=0;i<qts;i++)
            {
                seat+= (s+i)+", ";
            }
            
            code = "insert into ticket(flightID,NID) values("+fid+", "+NID+");";
            
            stmt.execute(code);
            
            r1 = stmt.executeQuery("select seat from flight where flightID ="+fid+";");
            r1.next();
            
            stmt.execute("update flight set seat ="+(qts+r1.getInt(1))+" where flightID ="+fid+";");
            code = "select ticketNo from ticket where flightID ="+fid+" and NID = "+NID+";";
            r1 = stmt.executeQuery(code);
            r1.next();

            tNo.setText(""+r1.getInt(1));
            ss.setText(seat);
            code = "select * from customer where NID ="+NID+";";
            System.out.println(code);
            r1 = stmt.executeQuery(code);
            r1.next(); 
           name.setText(r1.getString(1));
            nid.setText(r1.getString(2));
            sex.setText(r1.getString(4));
            phone.setText(r1.getString(5));
            
            r1 = stmt.executeQuery("select * from flight where flightID ="+fid+";");
            r1.next();
            dateMan ddd = new dateMan();
            date.setText(ddd.numToDate(r1.getString(4)));
            rid = ""+ r1.getString(2);
            String ss = r1.getString(5);
            shift.setText(ss.equals("1")? "day":"night");
            
            r1 = stmt.executeQuery("Select * from route where routeID ="+rid+";");
            r1.next();
            
            
            start.setText(r1.getString(2));
            end.setText(r1.getString(3));
            
//            
            JOptionPane.showMessageDialog(null, "success");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        nid = new javax.swing.JTextField();
        start = new javax.swing.JTextField();
        end = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        tNo = new javax.swing.JTextField();
        ss = new javax.swing.JTextField();
        shift = new javax.swing.JTextField();
        sex = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Back to Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 453, 124, 40));

        name.setText("name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 124, -1));

        nid.setText("NID");
        nid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nidActionPerformed(evt);
            }
        });
        getContentPane().add(nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 124, -1));

        start.setText("start");
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 124, -1));

        end.setText("end");
        getContentPane().add(end, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 124, -1));

        date.setText("date");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 124, -1));

        tNo.setText("ticNO");
        getContentPane().add(tNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 124, -1));

        ss.setText("seat");
        getContentPane().add(ss, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 124, -1));

        shift.setText("shift");
        shift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftActionPerformed(evt);
            }
        });
        getContentPane().add(shift, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 124, -1));

        sex.setText("gender");
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 124, -1));

        phone.setText("phone");
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 124, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ticketConfirm.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LandingPage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void shiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shiftActionPerformed

    private void nidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nidActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public String fid;
    public String rid;
    public String NID;
    public String seats;
    public String ticketNo;
    public int qts;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confirmTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confirmTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confirmTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confirmTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new confirmTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JTextField end;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nid;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField sex;
    private javax.swing.JTextField shift;
    private javax.swing.JTextField ss;
    private javax.swing.JTextField start;
    private javax.swing.JTextField tNo;
    // End of variables declaration//GEN-END:variables
}
