/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smarttransport;

import java.sql.*;
import javax.swing.JOptionPane;
import static smarttransport.admin.*;

/**
 *
 * @author mursalat
 */
public class oldTicket extends javax.swing.JFrame {

    /**
     * Creates new form oldTicket
     */
    public oldTicket() {
        initComponents();
        try
        {
            con = DriverManager.getConnection(server,"root", "awd@3456");
            stmt = (Statement) con.createStatement();
            stmt.execute("use smart;");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Connection Failed");
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        start = new javax.swing.JComboBox<>();
        end = new javax.swing.JComboBox<>();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        qts = new javax.swing.JComboBox<>();
        search = new javax.swing.JButton();
        confirm = new javax.swing.JButton();
        available = new javax.swing.JTextField();
        shift = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        Back.setText("Back to Home");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(80, 460, 130, 60);

        start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Dhaka", "Chittagong", "Sylhet" }));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start);
        start.setBounds(160, 50, 110, 40);

        end.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Dhaka", "Chittagong", "Sylhet" }));
        end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endActionPerformed(evt);
            }
        });
        getContentPane().add(end);
        end.setBounds(580, 40, 110, 50);

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(day);
        day.setBounds(160, 140, 110, 40);

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        getContentPane().add(month);
        month.setBounds(577, 130, 110, 50);

        qts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "1", "2", "3", "4" }));
        getContentPane().add(qts);
        qts.setBounds(600, 390, 100, 40);

        search.setText("Search Tickets");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(420, 230, 140, 40);

        confirm.setText("Confirm Ticket");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm);
        confirm.setBounds(600, 460, 101, 50);

        available.setText("ticket found");
        getContentPane().add(available);
        available.setBounds(450, 310, 90, 40);

        shift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Day", "Night" }));
        getContentPane().add(shift);
        shift.setBounds(157, 220, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/time_travel_clock_background_wallpaper.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 800, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LandingPage().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        
        
        q = qts.getSelectedIndex();
        System.out.println(nid+" "+fid+" "+q);
        if(q==0)
        {
            JOptionPane.showMessageDialog(null, "Please select the number of tickets you want to buy.");
        }
        else if(fid==null)
        {
            JOptionPane.showMessageDialog(null, "Please search for the ticket you want to buy.");
        }
        else
        {
            confirmTicket t = new confirmTicket();
            t.NID = this.nid;
            t.fid = this.fid;
            t.qts=q;
            price*= q;
            JOptionPane.showMessageDialog(null, "Ticket Brought.\nYou are charged "+price+"tk only");
            
            t.doTicket();
            this.setVisible(false);
            t.setVisible(true);
        }
    }//GEN-LAST:event_confirmActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        s = start.getSelectedIndex();
        e = end.getSelectedIndex();
        d = day.getSelectedIndex();
        m = month.getSelectedIndex();
        sh = shift.getSelectedIndex();
        String code;
        
        if(s==0 || e==0|| d==0||m==0 || sh ==0)
        {
            JOptionPane.showMessageDialog(null, "Please complete the information above");
        }
        else if(s==e)
        {
            JOptionPane.showMessageDialog(null, "Source and destination cannot be same!");
        }
        else if(d>date.size[m-1])
        {
            JOptionPane.showMessageDialog(null, "Invalid date");
        }
        else if(date.dateToNum(d, m)<date.today())
        {
            JOptionPane.showMessageDialog(null,"Our time machine is still in prototype stage.\nPlease select a date from future!");
        }
        else
        {
            try
            {
                code = "select seat, flightID from flight where routeID = ";
                code += ""+s+e+" and day = "+date.dateToNum(d, m)+" and shift = "+sh+";";
                
                System.out.println(code);
                r1 = stmt.executeQuery(code);
                r1.next();
                System.out.println(r1.getInt(1));
                if(r1.getInt(1)>39)
                {
                    JOptionPane.showMessageDialog(null, "Ticket to that date is not\navailable yet");
                }
                else
                {
                    int t = ((40-r1.getInt(1))>4? 4:(40-r1.getInt(1)));
                    JOptionPane.showMessageDialog(null, "Ticket found.\nYou can select max "+t+" tickets");
                    available.setText(""+t);
                    fid = ""+r1.getInt(2);
                    System.out.println(fid);
                    r1 = stmt.executeQuery("select price from route where routeID ="+s+e+";");
                    r1.next();
                    price = r1.getInt(1);
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_searchActionPerformed

    private void endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public int s,e,d,m,sh,price,q;
    public String nid = null;
    public String fid = null;
    public dateMan date = new dateMan();
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oldTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oldTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oldTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oldTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oldTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField available;
    private javax.swing.JButton confirm;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JComboBox<String> end;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JComboBox<String> qts;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> shift;
    private javax.swing.JComboBox<String> start;
    // End of variables declaration//GEN-END:variables
}
